### PR TITLE
[nemo-qml-plugin-configuration] Migrate to sailfish-qdoc-template. JB#54004

### PR DESCRIPTION
**Pull request by pvuorela**
@vigejolla @rainemak @Tomin1

### CODE REVIEW

**Comment by Tomin1** [comment]
Looks like doc/nemo-qml-plugin-configuration.qdocconf could use some updating. It still says nemomobile and copyright is from 2015.

**Comment by pvuorela** [comment]
Bit balancing here on what kind of changes I'm doing. The copyrights and such have a tendency to get into discussion that's not about the template usage :) For another thing I'm not sure how the html footer is actually used, gets into the html generated here, but commonly the qch file is only packaged and seems the docs on web haven't gotten that. Overall those parts feels even pointless as the years are soon too old so I think skipping the whole thing could make sense.

But that's a separate topic, hence being careful on what I'm adjusting.

Having that said, at least the url in qdocconf should be pretty uncontroversial. Guess nemomobile -> nemo should be just adapting to old api changes. Not sure what the namespace part for example affects, but anyway.

**Review by Tomin1 — APPROVED** [review]
LGTM.

**Comment by Tomin1** [comment]
> Having that said, at least the url in qdocconf should be pretty uncontroversial. Guess nemomobile -> nemo should be just adapting to old api changes. Not sure what the namespace part for example affects, but anyway.

Yeah, well, I think the url was the important bit. :+1:

**Pull request merged**
